services:
  postgres_db:
    container_name: postgres_db_container
    image: postgres:14
    restart: always
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    
    volumes:
      - pg_db_vol:/var/lib/postgresql/data
    networks:
      - mydjangocomposenetwork

  web_services:
    container_name: django_compose_container
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - postgres_db

    ports: 
      - "${DJANGO_LOCAL_PORT}:${DJANGO_DOCKER_PORT}"

    environment: 
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    
    volumes:
      - django_app_vol:/app
    
    networks:
      - mydjangocomposenetwork

volumes:
  pg_db_vol:
  django_app_vol:

networks:
  mydjangocomposenetwork: